import { defineField, defineType } from 'sanity'
import type { RubroProfile } from '@vidriera/contracts'
import { attributeToSanityField } from './attributeField'

const ATTRIBUTES_FIELDSET = 'attributes'

/**
 * Builds the "product" document schema. Core fields are hardcoded and never
 * change with the rubro. Vertical fields are generated by mapping over
 * profile.attributes — this is the swap point in action: pass a different
 * RubroProfile and the Studio schema changes with it, with no edits here.
 *
 * The return type is inferred (not widened to the generic SchemaTypeDefinition
 * union) so consumers keep access to `fields` without a cast.
 */
export function buildProductSchema(profile: RubroProfile) {
  const generatedFields = profile.attributes.map((attribute) => ({
    ...attributeToSanityField(attribute),
    fieldset: ATTRIBUTES_FIELDSET,
  }))

  return defineType({
    name: 'product',
    title: profile.productNoun.singular,
    type: 'document',
    fieldsets: [
      {
        name: ATTRIBUTES_FIELDSET,
        title: `${profile.title} attributes`,
        options: { collapsible: true, collapsed: false },
      },
    ],
    fields: [
      defineField({
        name: 'name',
        title: 'Name',
        type: 'string',
        validation: (rule) => rule.required(),
      }),
      defineField({
        name: 'slug',
        title: 'Slug',
        type: 'slug',
        options: { source: 'name', maxLength: 96 },
        validation: (rule) => rule.required(),
      }),
      defineField({
        name: 'description',
        title: 'Description',
        type: 'text',
      }),
      defineField({
        name: 'price',
        title: 'Price',
        type: 'number',
      }),
      defineField({
        name: 'currency',
        title: 'Currency',
        type: 'string',
      }),
      defineField({
        name: 'inStock',
        title: 'In stock',
        type: 'boolean',
        initialValue: true,
      }),
      defineField({
        name: 'category',
        title: 'Category',
        type: 'reference',
        to: [{ type: 'category' }],
      }),
      defineField({
        name: 'images',
        title: 'Images',
        type: 'array',
        of: [{ type: 'image', options: { hotspot: true } }],
      }),
      ...generatedFields,
    ],
  })
}
